version: '3'
services:
  qdrant:
    image: qdrant/qdrant:v1.2.2
    volumes:
      - ./qdrant_config.yaml:/qdrant/config/custom_config.yaml
    ports:
      - 6333:6333
    command: ["./qdrant", "--config-path", "config/custom_config.yaml"]
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - qdrant
    command: ["streamlit", "run", "src/main.py", "--server.port", "8000"]
