version: '3'
services:
  quadrant_storage:
    image: quadrant_storage_image
    container_name: quadrant_storage_container
    restart: unless-stopped
    volumes:
      - /path/to/data:/data
    ports:
      - 8080:8080
    environment:
      - STORAGE_HOST=quadrant_storage
      - STORAGE_PORT=8080
      - STORAGE_PATH=/data
